// This file was generated by Prisma and assumes you have installed the following:
import "dotenv/config";
import {config} from './src/config.js';

import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx src/seed.ts"
  },
  datasource: {
    url: config.databaseUrl,
  },
});
